sed -i 's/float_num/floatNum/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/host_chat_id/hostChatId/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/product_name/productName/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/product_counts/productCounts/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/product_amount/productAmount/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/occur_time/occurTime/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/due_pay_date/duePayDate/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/payout_time/payoutTime/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/cust_chat_id/custChatId/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/payment_status/paymentStatus/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/check_status/checkStatus/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/floatnum/floatNum/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/hostchatid/hostChatId/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/productname/productName/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/productcounts/productCounts/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/productamount/productAmount/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/occurtime/occurTime/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/duepaydate/duePayDate/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/payouttime/payoutTime/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/custchatid/custChatId/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/paymentstatus/paymentStatus/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/checkstatus/checkStatus/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/check_time/checkTime/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/host_uuid/hostUuid/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/cust_uuid/custUuid/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/checktime/checkTime/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/hostuuid/hostUuid/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/custuuid/custUuid/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
sed -i 's/record_t/record/g' .\\src\\com\\szb\\mapping\\RecordMapper.xml
echo ".\\src\\com\\szb\\mapping\\RecordMapper.xml的替换工作完成"