sed -i 's/user_name/userName/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/telephone/telephone/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/shop_address/shopAddress/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/home_address/homeAddress/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/user_type/userType/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/chat_id/chatId/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/username/userName/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/telephone/telephone/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/shopaddress/shopAddress/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/homeaddress/homeAddress/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/usertype/userType/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/chatid/chatId/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/shopname/shopName/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/shop_name/shopName/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/qrcodeaddress/qrCodeAddress/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/qr_code_address/qrCodeAddress/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/headportraitaddress/headPortraitAddress/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/head_portrait_address/headPortraitAddress/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/nick_name/nickName/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/regist_time/registTime/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/change_time/changeTime/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/nickname/nickName/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/registtime/registTime/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/changetime/changeTime/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
sed -i 's/user_t/user/g' .\\src\\com\\szb\\mapping\\UserMapper.xml
echo ".\\src\\com\\szb\mapping\\UserMapper.xml的替换工作完成"